// Gamepad buttons constants
this.creatine.pad = {
  A          : 0,
  B          : 1,
  X          : 2,
  Y          : 3,
  LB         : 4,
  RB         : 5,
  LT         : 6,
  RT         : 7,
  SELECT     : 8,
  START      : 9,
  LEFTSTICK  : 10,
  RIGHTSTICK : 11,
  UP         : 12,
  DOWN       : 13,
  LEFT       : 14,
  RIGHT      : 15,
  META       : 16,
};